import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [],
  safelist: [
    'i-carbon-character-whole-number',
    'i-carbon-cross-tab',
    'i-carbon-document-pdf',
    'i-carbon-language',
    'i-carbon-map',
    'i-carbon-move',
    'i-carbon-row-insert',
    'i-carbon-star-review',
    'i-carbon-tool-box',
    'i-ep-edit-pen',
    'i-ep-magic-stick',
    'i-ep-menu',
    'i-logos-adobe',
    'i-logos-astro',
    'i-logos-chrome',
    'i-logos-docker-icon',
    'i-logos-element',
    'i-logos-git-icon',
    'i-logos-gitlab',
    'i-logos-hexo',
    'i-logos-intellij-idea',
    'i-logos-java',
    'i-logos-markdown',
    'i-logos-microsoft-icon',
    'i-logos-mongodb-icon',
    'i-logos-nodejs-icon',
    'i-logos-nvidia',
    'i-logos-openai-icon',
    'i-logos-python',
    'i-logos-stability-ai-icon',
    'i-logos-tailwindcss-icon',
    'i-logos-terminal',
    'i-logos-typescript-icon',
    'i-logos-ubuntu',
    'i-logos-unocss',
    'i-logos-visual-studio-code',
    'i-logos-vitejs',
    'i-logos-vue',
    'i-logos-vueuse',
    'i-twemoji-beaming-face-with-smiling-eyes',
    'i-twemoji-blue-book',
    'i-twemoji-books',
    'i-twemoji-calendar',
    'i-twemoji-camera',
    'i-twemoji-hammer-and-wrench',
    'i-twemoji-letter-c',
    'i-twemoji-link',
    'i-twemoji-memo',
    'i-twemoji-open-file-folder',
    'i-twemoji-party-popper',
    'i-twemoji-red-question-mark',
    'i-twemoji-rocket',
    'i-twemoji-skateboard',
    'i-twemoji-spiral-notepad',
    'i-twemoji-toolbox',
    'i-vscode-icons-file-type-jenkins',
    'svg-admin3',
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
    }),
    presetTypography(),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
