import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [],
  safelist: [
    'i-carbon-character-whole-number',
    'i-carbon-cross-tab',
    'i-carbon-document-pdf',
    'i-carbon-language',
    'i-carbon-map',
    'i-carbon-move',
    'i-carbon-row-insert',
    'i-carbon-star-review',
    'i-carbon-tool-box',
    'i-ep-edit-pen',
    'i-ep-magic-stick',
    'i-ep-menu',
    'i-logos-gitlab',
    'i-logos-github-icon',
    'i-twemoji-beaming-face-with-smiling-eyes',
    'i-twemoji-blue-book',
    'i-twemoji-books',
    'i-twemoji-calendar',
    'i-twemoji-camera',
    'i-twemoji-hammer-and-wrench',
    'i-twemoji-letter-c',
    'i-twemoji-link',
    'i-twemoji-memo',
    'i-twemoji-open-file-folder',
    'i-twemoji-party-popper',
    'i-twemoji-red-question-mark',
    'i-twemoji-rocket',
    'i-twemoji-skateboard',
    'i-twemoji-spiral-notepad',
    'i-twemoji-toolbox',
    'i-vscode-icons-file-type-jenkins',
    'svg-admin3',
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
    }),
    presetTypography(),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
